# Dockerfile.frontend

FROM python:3.13-slim

WORKDIR /streamlit_app

# Install system dependencies
RUN apt-get update && apt-get install -y bash

# Install Python dependencies
COPY requirements.frontend.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.frontend.txt

# Copy frontend Streamlit app code
COPY ./streamlit_app .

# Expose Streamlit port
EXPOSE 8501

# Start Streamlit app
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
