"""create users tables

Revision ID: 00bfe1da15d7
Revises: 1ca57c78eddd
Create Date: 2025-04-26 16:22:03.849686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bfe1da15d7'
down_revision: Union[str, None] = '1ca57c78eddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_info', sa.Column('is_recruiter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'is_recruiter')
    # ### end Alembic commands ###
