"""create users tables

Revision ID: 1ca57c78eddd
Revises: 
Create Date: 2025-04-26 16:06:08.097130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca57c78eddd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_cred',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_cred_email'), 'users_cred', ['email'], unique=False)
    op.create_table('users_info',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('resume', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users_cred.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_info_email'), 'users_info', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_info_email'), table_name='users_info')
    op.drop_table('users_info')
    op.drop_index(op.f('ix_users_cred_email'), table_name='users_cred')
    op.drop_table('users_cred')
    # ### end Alembic commands ###
