[theme]
base="dark"
primaryColor="#4CAF50"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[server]
headless = true
runOnSave = true

[client]
showSidebarNavigation = false